"""
Re-export shim: the metric oracles now live in :mod:`tests_new.metrics.oracles`.

The naive reference implementations were consolidated into the ``tests_new`` home during the contract-suite
redesign; this thin package keeps the legacy ``from tests.metrics.oracles import <name>_reference`` path
working for the existing suite until its cutover. See ``tests_new/DESIGN.md``.
"""

# The oracle *modules* live in the new home; extend this shim package's search path so the legacy per-module
# path ``tests.metrics.oracles.<name>`` (imported dynamically by ``tests.test_policies``) resolves there too.
from tests_new.metrics.oracles import __path__ as _new_oracles_path
from tests_new.metrics.oracles import (
    adjusted_sharpe_ratio_reference,
    alpha_reference,
    alpha_rolling_reference,
    beta_reference,
    beta_rolling_reference,
    burke_ratio_reference,
    cagr_reference,
    cagr_rolling_reference,
    calmar_ratio_reference,
    capture_downside_ratio_reference,
    capture_ratio_reference,
    capture_upside_ratio_reference,
    common_sense_ratio_reference,
    conditional_drawdown_at_risk_reference,
    conditional_value_at_risk_reference,
    downside_deviation_reference,
    downside_deviation_rolling_reference,
    drawdown_reference,
    drawdown_rolling_reference,
    gain_to_pain_ratio_reference,
    information_ratio_reference,
    information_ratio_rolling_reference,
    kelly_criterion_reference,
    kurtosis_reference,
    kurtosis_rolling_reference,
    max_drawdown_duration_reference,
    max_drawdown_reference,
    modigliani_risk_adjusted_performance_reference,
    omega_ratio_reference,
    omega_ratio_rolling_reference,
    pain_index_reference,
    pain_ratio_reference,
    payoff_ratio_reference,
    probabilistic_sharpe_ratio_reference,
    profit_factor_reference,
    recovery_ratio_reference,
    risk_of_ruin_reference,
    sharpe_ratio_reference,
    sharpe_ratio_rolling_reference,
    skewness_reference,
    skewness_rolling_reference,
    sortino_ratio_reference,
    sortino_ratio_rolling_reference,
    stability_reference,
    sterling_ratio_reference,
    tail_ratio_reference,
    tail_ratio_rolling_reference,
    total_return_reference,
    total_return_rolling_reference,
    treynor_ratio_reference,
    treynor_ratio_rolling_reference,
    ulcer_index_reference,
    ulcer_performance_ratio_reference,
    value_at_risk_modified_reference,
    value_at_risk_parametric_reference,
    value_at_risk_reference,
    value_at_risk_rolling_reference,
    volatility_reference,
    volatility_rolling_reference,
    win_rate_reference,
)

__path__ = [*__path__, *_new_oracles_path]

__all__ = (
    "adjusted_sharpe_ratio_reference",
    "alpha_reference",
    "alpha_rolling_reference",
    "beta_reference",
    "beta_rolling_reference",
    "burke_ratio_reference",
    "cagr_reference",
    "cagr_rolling_reference",
    "calmar_ratio_reference",
    "capture_downside_ratio_reference",
    "capture_ratio_reference",
    "capture_upside_ratio_reference",
    "common_sense_ratio_reference",
    "conditional_drawdown_at_risk_reference",
    "conditional_value_at_risk_reference",
    "downside_deviation_reference",
    "downside_deviation_rolling_reference",
    "drawdown_reference",
    "drawdown_rolling_reference",
    "gain_to_pain_ratio_reference",
    "information_ratio_reference",
    "information_ratio_rolling_reference",
    "kelly_criterion_reference",
    "kurtosis_reference",
    "kurtosis_rolling_reference",
    "max_drawdown_duration_reference",
    "max_drawdown_reference",
    "modigliani_risk_adjusted_performance_reference",
    "omega_ratio_reference",
    "omega_ratio_rolling_reference",
    "pain_index_reference",
    "pain_ratio_reference",
    "payoff_ratio_reference",
    "probabilistic_sharpe_ratio_reference",
    "profit_factor_reference",
    "recovery_ratio_reference",
    "risk_of_ruin_reference",
    "sharpe_ratio_reference",
    "sharpe_ratio_rolling_reference",
    "skewness_reference",
    "skewness_rolling_reference",
    "sortino_ratio_reference",
    "sortino_ratio_rolling_reference",
    "stability_reference",
    "sterling_ratio_reference",
    "tail_ratio_reference",
    "tail_ratio_rolling_reference",
    "total_return_reference",
    "total_return_rolling_reference",
    "treynor_ratio_reference",
    "treynor_ratio_rolling_reference",
    "ulcer_index_reference",
    "ulcer_performance_ratio_reference",
    "value_at_risk_modified_reference",
    "value_at_risk_parametric_reference",
    "value_at_risk_reference",
    "value_at_risk_rolling_reference",
    "volatility_reference",
    "volatility_rolling_reference",
    "win_rate_reference",
)
