"""
The consolidated test-support surface: the shared low-level helpers plus the spec framework the rungs delegate to.

The stateless helpers — one concern per module: :mod:`tests.support.asserts` (compare a result against an oracle),
:mod:`tests.support.bars` (transpose generated bars into columns), :mod:`tests.support.benchmarks` (time an
expression for the benchmark tier), :mod:`tests.support.columns` (canonical column-name constants),
:mod:`tests.support.frames` (materialize inputs into a frame and evaluate an expression),
:mod:`tests.support.strategies` (Hypothesis input generators),
:mod:`tests.support.synthesis` (signature-driven call synthesis for the public factories),
:mod:`tests.support.tolerances` (the named floating-point tolerance ladder and :func:`input_scale`) — are
re-exported flat here alongside the spec framework's frozen data types and engine (:mod:`tests.support.spec`), so
every test imports from one place. They are plain functions rather than pytest fixtures so they compose with Hypothesis
``@given`` without leaking state across generated examples. See ``tests/README.md``.
"""

from tests.support.asserts import assert_matches, assert_scale_homogeneous
from tests.support.bars import split_pairs, split_quads, split_triples
from tests.support.benchmarks import fastest_eval
from tests.support.columns import BENCHMARK, CLOSE, COLUMN_X, HIGH, LOW, RETURNS
from tests.support.frames import apply_expr, count_leading_nulls, materialize
from tests.support.spec import (
    SPEC_LANE,
    SPEC_SCALAR,
    Deviant,
    ScaleAxis,
    ScaleExempt,
    Shape,
    Spec,
    SpecPin,
    actual_lanes,
    build_expr,
    flat,
    fuzz_frames,
    horizon,
    lane_series,
    probe_frame,
    probe_length,
    reference_lanes,
    spec_id,
    widest_warmup,
)
from tests.support.strategies import (
    SUBNORMAL_FLOOR,
    coherent_hl,
    coherent_hl_with_missing,
    coherent_hlc,
    coherent_hlc_with_missing,
    coherent_hlcv,
    coherent_hlcv_with_missing,
    coherent_ohlc,
    coherent_ohlc_with_missing,
    finite_floats,
    missing_data_floats,
    spans_even_lag_run,
    standardized_moment_floats,
    subnormal_safe_floats,
    well_spread,
    windows_well_conditioned,
    windows_well_spread,
)
from tests.support.synthesis import synthesize_call
from tests.support.tolerances import (
    ABSOLUTE_TOLERANCE_EXACT,
    ABSOLUTE_TOLERANCE_PROPERTY,
    ABSOLUTE_TOLERANCE_REFERENCE,
    ABSOLUTE_TOLERANCE_ROLLING_ORACLE,
    ABSOLUTE_TOLERANCE_STREAMING,
    EXACT_TOLERANCE_FACTOR,
    RELATIVE_TOLERANCE_EXACT,
    RELATIVE_TOLERANCE_PROPERTY,
    RELATIVE_TOLERANCE_REFERENCE,
    RELATIVE_TOLERANCE_ROLLING_ORACLE,
    RELATIVE_TOLERANCE_SCALE,
    input_scale,
    streaming_abs_tol,
)

__all__ = (
    "ABSOLUTE_TOLERANCE_EXACT",
    "ABSOLUTE_TOLERANCE_PROPERTY",
    "ABSOLUTE_TOLERANCE_REFERENCE",
    "ABSOLUTE_TOLERANCE_ROLLING_ORACLE",
    "ABSOLUTE_TOLERANCE_STREAMING",
    "BENCHMARK",
    "CLOSE",
    "COLUMN_X",
    "EXACT_TOLERANCE_FACTOR",
    "HIGH",
    "LOW",
    "RELATIVE_TOLERANCE_EXACT",
    "RELATIVE_TOLERANCE_PROPERTY",
    "RELATIVE_TOLERANCE_REFERENCE",
    "RELATIVE_TOLERANCE_ROLLING_ORACLE",
    "RELATIVE_TOLERANCE_SCALE",
    "RETURNS",
    "SPEC_LANE",
    "SPEC_SCALAR",
    "SUBNORMAL_FLOOR",
    "Deviant",
    "ScaleAxis",
    "ScaleExempt",
    "Shape",
    "Spec",
    "SpecPin",
    "actual_lanes",
    "apply_expr",
    "assert_matches",
    "assert_scale_homogeneous",
    "build_expr",
    "coherent_hl",
    "coherent_hl_with_missing",
    "coherent_hlc",
    "coherent_hlc_with_missing",
    "coherent_hlcv",
    "coherent_hlcv_with_missing",
    "coherent_ohlc",
    "coherent_ohlc_with_missing",
    "count_leading_nulls",
    "fastest_eval",
    "finite_floats",
    "flat",
    "fuzz_frames",
    "horizon",
    "input_scale",
    "lane_series",
    "materialize",
    "missing_data_floats",
    "probe_frame",
    "probe_length",
    "reference_lanes",
    "spans_even_lag_run",
    "spec_id",
    "split_pairs",
    "split_quads",
    "split_triples",
    "standardized_moment_floats",
    "streaming_abs_tol",
    "subnormal_safe_floats",
    "synthesize_call",
    "well_spread",
    "widest_warmup",
    "windows_well_conditioned",
    "windows_well_spread",
)
