"""
The edge-case contract registry -- the single source of truth for every public function's testable profile.

Each public factory has exactly one :class:`FunctionProfile` row, keyed by name. A row is not documentation *about* a
function; it is the **declaration** a function makes about how it must be tested -- its shape, its domain, and, above
all, its ``null`` / ``NaN`` **policy**. The shared contract suite reads this map and tests every function *by its
declared policy*, so the whole package is exercised uniformly from one place while each function's genuine differences
are stated explicitly rather than left to drift between files.

That last point is the whole design. Edge cases cannot be tested identically everywhere -- an EMA bridges an interior
``null`` where a rolling mean nulls its window, and a reducing ratio simply skips it. Those are real, subtle differences
in behaviour. The registry makes each one an **explicit, documented variant**: a function that departs from the
pointwise baseline says so in a single, typed field, and ``tests/POLICY.md`` defines exactly what that field means.
A contributor opening two families side by side never has to hold "which edge is tested how, where" in their head --
they read the row.

The map is kept honest by :mod:`tests.test_registry`, the self-check: it asserts the registry is in bijection with the
three public ``__all__`` tuples (no function missing, no orphan row), that every declared oracle is importable, and --
the load-bearing guarantee -- that each function's *actual* ``null`` / ``NaN`` behaviour matches the policy it declares
here. A row that lies about its function is a red build, not a finding for the next audit.

The axes (each defined crisply, with its per-member meaning, in ``tests/POLICY.md``):

- **macro** -- the family the function belongs to.
- **shape** -- ``REDUCING`` (series -> one scalar), ``ELEMENTWISE`` (series -> series), or ``STRUCT`` (multi-line).
- **domain** / **columns** -- the input the function consumes; ``columns`` lists the OHLCV subset for ``OHLCV`` domains.
- **windowed** -- whether the function takes a lookback ``window``.
- **null_policy** -- what an interior ``null`` does: ``SKIPPED`` (dropped from a reduction), ``PROPAGATES`` (nulls only
  its own row), ``IN_WINDOW_IS_NULL`` (nulls every window that overlaps it, then recovers), ``BRIDGED`` (a recursion
  steps over it and carries on), or ``LATCHES`` (contaminates every later row).
- **nan_policy** -- what an interior ``NaN`` does: ``POISONS`` (a reduction goes ``NaN``), ``PROPAGATES`` (nans only the
  rows it reaches, then recovers), or ``LATCHES`` (a recursion carries it forward forever).
- **oracle** -- the name of the independent ``*_reference`` implementation in ``tests/<macro>/oracles/``, or ``None``
  where correctness is pinned by component-definition / golden masters instead.

A **scale** axis (per-input rescaling homogeneity and boundedness) is deliberately not modelled here yet: it needs a
richer per-input-degree representation (a variance is degree-2, a VWAP is degree-1 in price and degree-0 in volume) and
is verified by the numeric scale contract, so it lands as its own follow-up alongside that contract -- see
``tests/POLICY.md``.
"""

from enum import Enum
from typing import NamedTuple


class Macro(Enum):
    """The public family a function belongs to."""

    INDICATORS = "indicators"
    PNL = "pnl"
    METRICS = "metrics"


class Shape(Enum):
    """How the output length relates to the input length."""

    REDUCING = "reducing"  # a series collapses to one scalar (one row per group under ``.over``)
    ELEMENTWISE = "elementwise"  # a series maps to a same-length series
    STRUCT = "struct"  # a multi-line output, one ``pl.Struct`` column


class Domain(Enum):
    """The kind of input the function consumes."""

    SINGLE = "single"  # one price/return series
    PAIRED = "paired"  # a returns series against a benchmark series
    OHLCV = "ohlcv"  # a subset of open/high/low/close/volume (see ``columns``)
    EQUITY = "equity_curve"  # a compounded equity curve


class NullPolicy(Enum):
    """What an interior ``null`` does to the output (see ``tests/POLICY.md`` for the full definition of each)."""

    SKIPPED = "skipped"  # excluded from the reduction; the result is as if the null were absent
    PROPAGATES = "propagates"  # nulls only its own output row (a pointwise map)
    IN_WINDOW_IS_NULL = "in_window_is_null"  # nulls every window that overlaps it, then recovers
    BRIDGED = "bridged"  # a recursion steps over it (state carries), so later rows recover
    LATCHES = "latches"  # contaminates every subsequent row


class NanPolicy(Enum):
    """What an interior ``NaN`` does to the output (see ``tests/POLICY.md`` for the full definition of each)."""

    POISONS = "poisons"  # a reduction goes ``NaN``
    PROPAGATES = "propagates"  # nans the rows it reaches, then recovers
    LATCHES = "latches"  # a recursion carries it forward forever


class FunctionProfile(NamedTuple):
    """One public function's testable profile -- the row the shared contracts read to test it by its own rules."""

    macro: Macro
    shape: Shape
    domain: Domain
    columns: frozenset[str]
    windowed: bool
    null_policy: NullPolicy
    nan_policy: NanPolicy
    oracle: str | None


REGISTRY: dict[str, FunctionProfile] = {
    # -- indicators ----------------------------------------------------------------------------------------------------
    "absolute_price_oscillator": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="absolute_price_oscillator_reference",
    ),
    "accumulation_distribution": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low", "volume"}),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="accumulation_distribution_reference",
    ),
    "accumulation_distribution_oscillator": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low", "volume"}),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="accumulation_distribution_oscillator_reference",
    ),
    "adx": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="adx_reference",
    ),
    "adxr": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="adxr_reference",
    ),
    "aroon": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="aroon_reference",
    ),
    "aroon_oscillator": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="aroon_oscillator_reference",
    ),
    "atr": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="atr_reference",
    ),
    "atr_normalized": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="atr_normalized_reference",
    ),
    "awesome_oscillator": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=False,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="awesome_oscillator_reference",
    ),
    "balance_of_power": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low", "open"}),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="balance_of_power_reference",
    ),
    "bollinger_bands": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="bollinger_bands_reference",
    ),
    "cci": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cci_reference",
    ),
    "chaikin_money_flow": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low", "volume"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="chaikin_money_flow_reference",
    ),
    "chande_momentum_oscillator": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="chande_momentum_oscillator_reference",
    ),
    "dema": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="dema_reference",
    ),
    "di_minus": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="di_minus_reference",
    ),
    "di_plus": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="di_plus_reference",
    ),
    "dm_minus": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="dm_minus_reference",
    ),
    "dm_plus": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="dm_plus_reference",
    ),
    "dominant_cycle_period": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.LATCHES,
        nan_policy=NanPolicy.LATCHES,
        oracle=None,
    ),
    "dominant_cycle_phase": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.LATCHES,
        nan_policy=NanPolicy.LATCHES,
        oracle=None,
    ),
    "donchian_channels": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="donchian_channels_reference",
    ),
    "dx": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="dx_reference",
    ),
    "ema": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="ema_reference",
    ),
    "fisher_transform": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="fisher_transform_reference",
    ),
    "hilbert_phasor": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.LATCHES,
        nan_policy=NanPolicy.LATCHES,
        oracle=None,
    ),
    "hilbert_trendline": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.LATCHES,
        nan_policy=NanPolicy.LATCHES,
        oracle=None,
    ),
    "hma": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="hma_reference",
    ),
    "ichimoku": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=False,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="ichimoku_reference",
    ),
    "kama": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="kama_reference",
    ),
    "keltner_channels": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="keltner_channels_reference",
    ),
    "linear_regression": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="linear_regression_reference",
    ),
    "linear_regression_angle": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="linear_regression_angle_reference",
    ),
    "linear_regression_intercept": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="linear_regression_intercept_reference",
    ),
    "linear_regression_slope": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="linear_regression_slope_reference",
    ),
    "macd": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="macd_reference",
    ),
    "mama": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.LATCHES,
        nan_policy=NanPolicy.LATCHES,
        oracle=None,
    ),
    "midpoint": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="midpoint_reference",
    ),
    "midprice": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="midprice_reference",
    ),
    "mom": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="mom_reference",
    ),
    "money_flow_index": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low", "volume"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="money_flow_index_reference",
    ),
    "obv": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"volume"}),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="obv_reference",
    ),
    "parabolic_sar": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="parabolic_sar_reference",
    ),
    "percentage_price_oscillator": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="percentage_price_oscillator_reference",
    ),
    "price_average": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low", "open"}),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="price_average_reference",
    ),
    "price_median": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"high", "low"}),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="price_median_reference",
    ),
    "price_typical": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="price_typical_reference",
    ),
    "price_weighted_close": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="price_weighted_close_reference",
    ),
    "rma": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="rma_reference",
    ),
    "roc": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="roc_reference",
    ),
    "rsi": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="rsi_reference",
    ),
    "rsi_stochastic": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="rsi_stochastic_reference",
    ),
    "sine_wave": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.LATCHES,
        nan_policy=NanPolicy.LATCHES,
        oracle=None,
    ),
    "sma": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="sma_reference",
    ),
    "standard_deviation_ewma": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="standard_deviation_ewma_reference",
    ),
    "standard_deviation_rolling": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="standard_deviation_rolling_reference",
    ),
    "stochastic_fast": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=False,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="stochastic_fast_reference",
    ),
    "stochastic_slow": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=False,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="stochastic_slow_reference",
    ),
    "supertrend": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="supertrend_reference",
    ),
    "t3": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="t3_reference",
    ),
    "tema": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="tema_reference",
    ),
    "time_series_forecast": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="time_series_forecast_reference",
    ),
    "trend_mode": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.LATCHES,
        nan_policy=NanPolicy.LATCHES,
        oracle=None,
    ),
    "trima": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="trima_reference",
    ),
    "trix": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="trix_reference",
    ),
    "true_range": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="true_range_reference",
    ),
    "ultimate_oscillator": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=False,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="ultimate_oscillator_reference",
    ),
    "variance_ewma": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="variance_ewma_reference",
    ),
    "variance_rolling": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="variance_rolling_reference",
    ),
    "vortex": FunctionProfile(
        Macro.INDICATORS,
        Shape.STRUCT,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="vortex_reference",
    ),
    "vwap": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low", "volume"}),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="vwap_reference",
    ),
    "vwma": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"volume"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="vwma_reference",
    ),
    "williams_r": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.OHLCV,
        frozenset({"close", "high", "low"}),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="williams_r_reference",
    ),
    "wma": FunctionProfile(
        Macro.INDICATORS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="wma_reference",
    ),
    # -- pnl -----------------------------------------------------------------------------------------------------------
    "cost_borrow": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cost_borrow_reference",
    ),
    "cost_fixed": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cost_fixed_reference",
    ),
    "cost_funding": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cost_funding_reference",
    ),
    "cost_notional": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cost_notional_reference",
    ),
    "cost_per_share": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cost_per_share_reference",
    ),
    "cost_proportional": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cost_proportional_reference",
    ),
    "cost_slippage": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cost_slippage_reference",
    ),
    "cumulative_pnl": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="cumulative_pnl_reference",
    ),
    "dividend": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="dividend_reference",
    ),
    "equity_curve": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.BRIDGED,
        nan_policy=NanPolicy.LATCHES,
        oracle="equity_curve_reference",
    ),
    "pnl_gross": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="pnl_gross_reference",
    ),
    "pnl_gross_inverse": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="pnl_gross_inverse_reference",
    ),
    "pnl_net": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="pnl_net_reference",
    ),
    "returns_gross": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="returns_gross_reference",
    ),
    "returns_log": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="returns_log_reference",
    ),
    "returns_net": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="returns_net_reference",
    ),
    "returns_simple": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="returns_simple_reference",
    ),
    "turnover": FunctionProfile(
        Macro.PNL,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="turnover_reference",
    ),
    # -- metrics -------------------------------------------------------------------------------------------------------
    "adjusted_sharpe_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="adjusted_sharpe_ratio_reference",
    ),
    "alpha": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="alpha_reference",
    ),
    "alpha_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.PAIRED,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="alpha_rolling_reference",
    ),
    "beta": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="beta_reference",
    ),
    "beta_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.PAIRED,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="beta_rolling_reference",
    ),
    "burke_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="burke_ratio_reference",
    ),
    "cagr": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="cagr_reference",
    ),
    "cagr_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.EQUITY,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="cagr_rolling_reference",
    ),
    "calmar_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="calmar_ratio_reference",
    ),
    "capture_downside_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="capture_downside_ratio_reference",
    ),
    "capture_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="capture_ratio_reference",
    ),
    "capture_upside_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="capture_upside_ratio_reference",
    ),
    "common_sense_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="common_sense_ratio_reference",
    ),
    "conditional_drawdown_at_risk": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="conditional_drawdown_at_risk_reference",
    ),
    "conditional_value_at_risk": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="conditional_value_at_risk_reference",
    ),
    "downside_deviation": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="downside_deviation_reference",
    ),
    "downside_deviation_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="downside_deviation_rolling_reference",
    ),
    "drawdown": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="drawdown_reference",
    ),
    "drawdown_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.EQUITY,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="drawdown_rolling_reference",
    ),
    "gain_to_pain_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="gain_to_pain_ratio_reference",
    ),
    "information_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="information_ratio_reference",
    ),
    "information_ratio_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.PAIRED,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="information_ratio_rolling_reference",
    ),
    "kelly_criterion": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="kelly_criterion_reference",
    ),
    "kurtosis": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="kurtosis_reference",
    ),
    "kurtosis_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="kurtosis_rolling_reference",
    ),
    "max_drawdown": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="max_drawdown_reference",
    ),
    "max_drawdown_duration": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="max_drawdown_duration_reference",
    ),
    "modigliani_risk_adjusted_performance": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="modigliani_risk_adjusted_performance_reference",
    ),
    "omega_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="omega_ratio_reference",
    ),
    "omega_ratio_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="omega_ratio_rolling_reference",
    ),
    "pain_index": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="pain_index_reference",
    ),
    "pain_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="pain_ratio_reference",
    ),
    "payoff_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="payoff_ratio_reference",
    ),
    "probabilistic_sharpe_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="probabilistic_sharpe_ratio_reference",
    ),
    "profit_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="profit_ratio_reference",
    ),
    "recovery_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="recovery_ratio_reference",
    ),
    "risk_of_ruin": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="risk_of_ruin_reference",
    ),
    "sharpe_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="sharpe_ratio_reference",
    ),
    "sharpe_ratio_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="sharpe_ratio_rolling_reference",
    ),
    "skewness": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="skewness_reference",
    ),
    "skewness_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="skewness_rolling_reference",
    ),
    "sortino_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="sortino_ratio_reference",
    ),
    "sortino_ratio_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="sortino_ratio_rolling_reference",
    ),
    "stability": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="stability_reference",
    ),
    "sterling_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="sterling_ratio_reference",
    ),
    "tail_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="tail_ratio_reference",
    ),
    "tail_ratio_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="tail_ratio_rolling_reference",
    ),
    "total_return": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="total_return_reference",
    ),
    "total_return_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.EQUITY,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.PROPAGATES,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="total_return_rolling_reference",
    ),
    "treynor_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.PAIRED,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="treynor_ratio_reference",
    ),
    "treynor_ratio_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.PAIRED,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="treynor_ratio_rolling_reference",
    ),
    "ulcer_index": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="ulcer_index_reference",
    ),
    "ulcer_performance_ratio": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.EQUITY,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="ulcer_performance_ratio_reference",
    ),
    "value_at_risk": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="value_at_risk_reference",
    ),
    "value_at_risk_modified": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="value_at_risk_modified_reference",
    ),
    "value_at_risk_parametric": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="value_at_risk_parametric_reference",
    ),
    "value_at_risk_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="value_at_risk_rolling_reference",
    ),
    "volatility": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="volatility_reference",
    ),
    "volatility_rolling": FunctionProfile(
        Macro.METRICS,
        Shape.ELEMENTWISE,
        Domain.SINGLE,
        frozenset(),
        windowed=True,
        null_policy=NullPolicy.IN_WINDOW_IS_NULL,
        nan_policy=NanPolicy.PROPAGATES,
        oracle="volatility_rolling_reference",
    ),
    "win_rate": FunctionProfile(
        Macro.METRICS,
        Shape.REDUCING,
        Domain.SINGLE,
        frozenset(),
        windowed=False,
        null_policy=NullPolicy.SKIPPED,
        nan_policy=NanPolicy.POISONS,
        oracle="win_rate_reference",
    ),
}
